// Felt Dashboard Application
// Generated by Felt GIS Workbench

let felt;
let currentFilters = {};

async function initializeMap() {
    try {
        // Embed Felt map
        felt = await Felt.embed(
            document.getElementById('map'),
            'MQl9C759BRRVWr2Qg8qvzH2D',
            {
                ui: {
                    controls: {
                        zoom: true,
                        legend: true,
                        search: false,
                        share: true
                    }
                }
            }
        );

        console.log('Felt map loaded successfully');

        // Setup event listeners
        setupEventListeners();

        
        // Setup filters
        setupFilters();
        

        // Listen to map interactions
        felt.onPointerMove({
            handler: (event) => handlePointerMove(event)
        });

        felt.onLayerClick({
            handler: (event) => handleLayerClick(event)
        });

    } catch (error) {
        console.error('Failed to initialize map:', error);
        showError('Failed to load map. Please check your connection.');
    }
}


function setupFilters() {
    
    const filter0 = document.getElementById('filter-0');
    filter0.addEventListener('input', (e) => {
        currentFilters['mag'] = e.target.value;
        
        document.getElementById('filter-0-value').textContent = e.target.value;
        
        applyFilters();
    });
    
}

async function applyFilters() {
    // Apply filters to map layers
    console.log('Applying filters:', currentFilters);

    // TODO: Implement filtering with Felt SDK
    // This would use felt.setLayerFilters() when available
}


function handlePointerMove(event) {
    // Handle mouse movement over map
    if (event.features && event.features.length > 0) {
        // Show feature info on hover
        const feature = event.features[0];
        updateFeatureInfo(feature);
    }
}

function handleLayerClick(event) {
    // Handle click on map features
    if (event.features && event.features.length > 0) {
        const feature = event.features[0];
        console.log('Clicked feature:', feature);
        showFeatureDetails(feature);
    }
}

function updateFeatureInfo(feature) {
    const infoDiv = document.getElementById('feature-info');
    if (infoDiv) {
        infoDiv.innerHTML = `
            <div class="feature-preview">
                <h3>Hover Info</h3>
                <p>${JSON.stringify(feature.properties, null, 2)}</p>
            </div>
        `;
    }
}

function showFeatureDetails(feature) {
    const infoDiv = document.getElementById('feature-info');
    if (infoDiv) {
        infoDiv.innerHTML = `
            <div class="feature-details">
                <h3>Selected Feature</h3>
                <pre>${JSON.stringify(feature.properties, null, 2)}</pre>
            </div>
        `;
    }
}

function setupEventListeners() {
    // Add any additional event listeners here
    console.log('Event listeners setup complete');
}

function showError(message) {
    const mapContainer = document.getElementById('map');
    mapContainer.innerHTML = `
        <div class="error-message">
            <h2>⚠️ Error</h2>
            <p>${message}</p>
        </div>
    `;
}

// Initialize when DOM is ready
document.addEventListener('DOMContentLoaded', () => {
    initializeMap();
});